<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Agent.Core\Agent.Core.csproj" />
    <ProjectReference Include="..\..\src\Agent.Mcp\Agent.Mcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

</Project>
